
spring.application.name=Hitmatrix
spring.datasource.url=jdbc:postgresql://localhost:5432/ProjectS
spring.datasource.username=shivakumar
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.oauth2.client.registration.google.client-id=891197169873-k8rvmkvpna2tq6n1f13a3mb7t58gtf83.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}