-- Single-table, per-user application notifications.
CREATE TABLE IF NOT EXISTS public.notifications (
    notification_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type       VARCHAR(50)  NOT NULL,
    title            VARCHAR(160) NOT NULL,
    message          VARCHAR(500) NOT NULL,
    severity         VARCHAR(16)  NOT NULL DEFAULT 'INFO',
    recipient_type   VARCHAR(20)  NOT NULL,
    recipient_user_id BIGINT,
    recipient_role   VARCHAR(50),
    college_id       BIGINT,
    branch_id        BIGINT,
    course_id        BIGINT,
    section_id       BIGINT,
    action_url       VARCHAR(500),
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at       TIMESTAMP,
    read_at          TIMESTAMP,
    CONSTRAINT chk_notifications_severity CHECK (severity IN ('INFO', 'SUCCESS', 'WARNING', 'ERROR')),
    CONSTRAINT chk_notifications_recipient CHECK (recipient_type IN ('ALL', 'USER', 'ROLE', 'COLLEGE', 'BRANCH', 'COURSE', 'SECTION'))
);

ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS read_at TIMESTAMP;

-- Preserve read state for old direct-user notifications before removing the old table.
DO $$
BEGIN
    IF to_regclass('public.notification_reads') IS NOT NULL THEN
        UPDATE public.notifications n
        SET read_at = nr.read_at
        FROM public.notification_reads nr
        WHERE nr.notification_id = n.notification_id
          AND n.recipient_type = 'USER';
    END IF;
END $$;

-- Existing shared notifications cannot safely carry per-user read state in one row.
-- Expand each one to a dedicated row for every matching active user.
DO $$
BEGIN
    IF to_regclass('public.notification_reads') IS NOT NULL THEN
        EXECUTE $migration$
            INSERT INTO public.notifications (
                event_type, title, message, severity, recipient_type, recipient_user_id,
                recipient_role, college_id, branch_id, course_id, section_id,
                action_url, created_at, expires_at, read_at
            )
            SELECT n.event_type, n.title, n.message, n.severity, 'USER', u.user_id,
                   n.recipient_role, n.college_id, n.branch_id, n.course_id, n.section_id,
                   n.action_url, n.created_at, n.expires_at,
                   CASE WHEN nr.notification_read_id IS NULL THEN NULL ELSE nr.read_at END
            FROM public.notifications n
            JOIN public.users u ON COALESCE(u.active_row, true) = true AND (
                   n.recipient_type = 'ALL'
                OR (n.recipient_type = 'ROLE' AND EXISTS (
                    SELECT 1 FROM public.roles r
                    WHERE r.role_id = u.role_id AND r.role_name = n.recipient_role
                ))
                OR (n.recipient_type = 'COLLEGE' AND u.college_id = n.college_id)
                OR (n.recipient_type = 'BRANCH' AND u.branch_id = n.branch_id)
                OR (n.recipient_type = 'COURSE' AND u.course_id = n.course_id)
                OR (n.recipient_type = 'SECTION' AND u.section_id = n.section_id)
            )
            LEFT JOIN public.notification_reads nr
                   ON nr.notification_id = n.notification_id AND nr.user_id = u.user_id
            WHERE n.recipient_type <> 'USER'
        $migration$;
    END IF;
END $$;

DELETE FROM public.notifications
WHERE recipient_type <> 'USER'
  AND to_regclass('public.notification_reads') IS NOT NULL;
DROP TABLE IF EXISTS public.notification_reads;

CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON public.notifications(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_created
    ON public.notifications(recipient_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread
    ON public.notifications(recipient_user_id) WHERE read_at IS NULL;
