-- ============================================================
-- Application time tracking and inactivity-session schema.
--
-- Used by UserActivitySessionService to:
--   * count only active application time from capped heartbeats;
--   * pause tracking after five minutes of user inactivity;
--   * resume the same session when the user returns;
--   * expire authentication activity after thirty minutes idle.
--
-- Run once against the Hintmatrix PostgreSQL database before deploying the
-- matching backend. The statements are safe to run again.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.user_activity_sessions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_key          VARCHAR(36) NOT NULL,
    user_id              BIGINT      NOT NULL,
    status               VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    started_at           TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_heartbeat_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_interaction_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at             TIMESTAMP,
    total_active_seconds BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT uq_user_activity_sessions_key UNIQUE (session_key),
    CONSTRAINT fk_user_activity_sessions_user
        FOREIGN KEY (user_id) REFERENCES public.users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_user_activity_sessions_status
        CHECK (status IN ('ACTIVE', 'IDLE', 'CLOSED', 'EXPIRED')),
    CONSTRAINT chk_user_activity_sessions_total_time
        CHECK (total_active_seconds >= 0)
);

-- Used when a login starts a new session and closes any unfinished session
-- belonging to that user.
CREATE INDEX IF NOT EXISTS idx_user_activity_sessions_user_status
    ON public.user_activity_sessions (user_id, status);

-- Used by the scheduled cleanup that stops counting after missed heartbeats.
CREATE INDEX IF NOT EXISTS idx_user_activity_sessions_active_heartbeat
    ON public.user_activity_sessions (last_heartbeat_at)
    WHERE status = 'ACTIVE';

-- Used by the thirty-minute inactivity expiration cleanup.
CREATE INDEX IF NOT EXISTS idx_user_activity_sessions_open_interaction
    ON public.user_activity_sessions (last_interaction_at)
    WHERE status IN ('ACTIVE', 'IDLE');
